CREATE TABLE users (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  created_at datetime(3) NOT NULL,
  updated_at datetime(3) NOT NULL,
  username varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  first_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  avatar_url varchar(255) DEFAULT NULL,
  bio varchar(255) DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  mobile_no varchar(255) DEFAULT NULL,
  mobile_no_code varchar(255) DEFAULT NULL,
  birthday datetime DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  city varchar(255) DEFAULT NULL,
  background_image_url varchar(255) DEFAULT NULL,
  website_url varchar(255) DEFAULT NULL,
  occupation varchar(255) DEFAULT NULL,
  education varchar(255) DEFAULT NULL,
  email_verified_at datetime DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY idx_users_username (username),
  UNIQUE KEY idx_users_email (email),
  KEY idx_users_created_at (created_at),
  KEY idx_users_updated_at (updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
